name: Check inline styles

on:
  push: {}
  pull_request: {}

jobs:
  check-inline-styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set execute permissions for scripts
        run: |
          chmod +x ./scripts/check-inline-styles.sh
      - name: Run inline styles checker
        run: ./scripts/check-inline-styles.sh
